/*
 * Copyright (c) 2022 Leon Weinmann
 *
 * Licensed under the MIT License. You may not use
 * this file except in compliance with the License. You can obtain a copy
 * in the file LICENSE in the source distribution.
 */

#ifndef ERROR_STRINGS_H
#define ERROR_STRINGS_H

/* ERROR STRINGS */
#define CW_ERROR_STR_TEST "THIS IS A TEST ERROR"
#define CW_ERROR_STR_PARAM_MISSING_STR "Parameter is missing"

/* AEAD ERROR STRINGS */
#define CW_ERROR_STR_AEAD_GCM_IV_NOT_SET "GCM IV not set"
#define CW_ERROR_STR_AEAD_GCM_TAG_LEN_WRONG "GCM wrong tag Len -> needs to be 1 - 16 inclusive"
#define CW_ERROR_STR_AEAD_CCM_IV_LEN_WRONG "CCM wrong iv Len -> needs to be 7 - 13 inclusive"
#define CW_ERROR_STR_AEAD_CCM_TAG_LEN_WRONG "CCM wrong tag Len -> needs to be even between 4 - 16 inclusive"
#define CW_ERROR_STR_AEAD_CCM_INPUT_TOO_LARGE "CCM input greater than INT_MAX -> needs to be > 0 and <= INT_MAX"
#define CW_ERROR_STR_AEAD_OCB_IV_LEN_WRONG "OCB wrong iv len -> needs to be < 16"
#define CW_ERROR_STR_AEAD_OCB_TAG_LEN_WRONG "OCB wrong tag len -> length needs to be 16"
#define CW_ERROR_STR_AEAD_CHACHA_20_IV_LEN_WRONG "CHACHA_20 wrong iv len -> needs to be <= 12"
#define CW_ERROR_STR_AEAD_CHACHA_20_TAG_LEN_WRONG "CHACHA_20 wrong tag len -> needs to be <= 16"
#define CW_ERROR_STR_AEAD_UNKNOWN_ALGORITHM "AEAD Unknown algorithm id"
#define CW_ERROR_STR_AEAD_EVP_CIPHER_CTX_NEW "AEAD OPENSSL EVP_CIPHER_CTX_new failed"
#define CW_ERROR_STR_AEAD_EVP_CIPHER_INIT_EX2 "AEAD OPENSSL EVP_CipherInit_ex2 failed"
#define CW_ERROR_STR_AEAD_EVP_CIPHER_CTX_CTR_IV_LEN "AEAD OPENSSL EVP_CIPHER_CTX_ctrl when setting iv length"
#define CW_ERROR_STR_AEAD_EVP_CIPHER_CTX_CTR_SET_TAG "AEAD OPENSSL EVP_CIPHER_CTX_ctrl when setting tag"
#define CW_ERROR_STR_AEAD_EVP_CIPHER_UPDATE "AEAD OPENSSL EVP_CipherUpdate failed"
#define CW_ERROR_STR_AEAD_EVP_CIPHER_UPDATE_AAD "AEAD OPENSSL EVP_CipherUpdate failed when setting aad data"
#define CW_ERROR_STR_AEAD_EVP_CIPHER_FINAL_EX "AEAD OPENSSL EVP_CipherFinal_ex failed"
#define CW_ERROR_STR_AEAD_EVP_CIPHER_CTX_CTR_GET_TAG "AEAD OPENSSL EVP_CIPHER_CTX_ctrl when getting tag"
#define CW_ERROR_STR_AEAD_WRONG_KEY_LEN "AEAD wrong key len"
#define CW_ERROR_STR_AEAD_CCM_NOT_SUPPORTED_FOR_STREAM "CCM is not supported for stream interface"

/* EC ERROR STRINGS */
#define CW_ERROR_STR_ECC_OSSL_ENCODER_CTX_NEW_FOR_PKEY "EC OSSL_ENCODER_CTX_new_for_pkey failed"
#define CW_ERROR_STR_ECC_OSSL_ENCODER_CTX_SET_CIPHER "EC OSSL_ENCODER_CTX_set_cipher failed when setting cipher for serialization"
#define CW_ERROR_STR_ECC_OSSL_ENCODER_CTX_SET_PASSPHRASE "EC OSSL_ENCODER_CTX_set_passphrase failed when setting passphrase"
#define CW_ERROR_STR_ECC_OSSL_ENCODER_TO_FP "EC OSSL_ENCODER_to_fp failed"
#define CW_ERROR_STR_ECC_OSSL_DECODER_CTX_NEW_FOR_PKEY "EC OSSL_DECODER_CTX_new_for_pkey failed"
#define CW_ERROR_STR_ECC_OSSL_DECODER_CTX_SET_PASSPHRASE "EC OSSL_DECODER_CTX_set_passphrase failed when setting passphrase"
#define CW_ERROR_STR_ECC_OSSL_DECODER_FROM_FP "EC OSSL_DECODER_from_fp failed"
#define CW_ERROR_STR_ECC_EVP_MD_CTX_NEW "EC EVP_MD_CTX_new failed when signing"
#define CW_ERROR_STR_ECC_EVP_DIGEST_SIGN_INIT_EX "EC EVP_DigestSignInit_ex failed"
#define CW_ERROR_STR_ECC_EVP_DIGEST_SIGN_UPDATE "EC EVP_DigestSignUpdate failed"
#define CW_ERROR_STR_ECC_EVP_DIGEST_SIGN_FINAL "EC EVP_DigestSignFinal failed"
#define CW_ERROR_STR_ECC_EVP_DIGEST_VERIFY_INIT_EX "EC EVP_DigestVerifyInit_ex failed"
#define CW_ERROR_STR_ECC_EVP_DIGEST_VERIFY_UPDATE "EC EVP_DigestVerifyUpdate failed"
#define CW_ERROR_STR_ECC_EVP_DIGEST_VERIFY_FINAL "EC EVP_DigestVerifyFinal failed -> Signature is not vaild"
#define CW_ERROR_STR_ECC_EVP_PKEY_CTX_NEW_ID "EC EVP_PKEY_CTX_new_id failed"
#define CW_ERROR_STR_ECC_EVP_PKEY_KEYGEN_INIT "EC EVP_PKEY_keygen_init failed"
#define CW_ERROR_STR_ECC_EVP_PKEY_CTX_SET_EC_PARAMGEN_CURVE_NID "EC EVP_PKEY_CTX_set_ec_paramgen_curve_nid failed"
#define CW_ERROR_STR_ECC_EVP_PKEY_GENERATE "EC EVP_PKEY_generate failed"
#define CW_ERROR_STR_ECC_SIGN_MESSAGE_TO_SHORT "EC Sign message too short"
#define CW_ERROR_STR_ECC_VERIFY_MESSAGE_TO_SHORT "EC Verify message too short"
#define CW_ERROR_STR_ECC_DER_PASSPHRASE_NOT_ALLOWED "EC passphrase is not allowed when using DER"

/* ENCODE ERROR STRINGS */
#define CW_ERROR_STR_ENCODE_EVP_ENCODE_CTX_NEW "ENCODE EVP_ENCODE_CTX_new failed"
#define CW_ERROR_STR_ENCODE_EVP_ENCODE_UPDATE "ENCODE EVP_EncodeUpdate update failed"
#define CW_ERROR_STR_ENCODE_EVP_DECODE_UPDATE "ENCODE EVP_DecodeUpdate update failed"
#define CW_ERROR_STR_ENCODE_EVP_DECODE_FINAL "ENCODE EVP_DecodeFinal failed"
#define CW_ERROR_STR_ENCODE_STREAM_WRONG_MODE "ENCODE Wrong mode for stream initialization"
#define CW_ERROR_STR_ENCODE_NO_FILE_IN_PLACE_ALLOWED "ENCODE No file in place encoding or decoding allowed"

/* HASH ERROR STRINGS */
#define CW_ERROR_STR_HASH_EVP_MD_CTX_NEW "HASH EVP_MD_CTX_new failed"
#define CW_ERROR_STR_HASH_EVP_DIGEST_INIT_EX_2 "HASH EVP_DigestInit_ex failed"
#define CW_ERROR_STR_HASH_EVP_DIGEST_UPDATE "HASH EVP_DigestUpdate failed"
#define CW_ERROR_STR_HASH_EVP_DIGEST_FINAL_EX "HASH EVP_DigestFinal_ex failed"
#define CW_ERROR_STR_HASH_VERIFY_LEN_MISMATCH "HASH verify generated hash is of different length from passed in hash"
#define CW_ERROR_STR_HASH_VERIFY_HASH_MISMATCH "HASH verify generated hash which is different from passed in hash"
#define CW_ERROR_STR_HASH_STRING_TOO_LARGE "HASH input string too large -> Must not exceed UINT32_MAX"

/* KEY EXCHANGE ERROR STRINGS */
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_NEW_RAW_PUBLIC_KEY_EX_X25519 "KEY_EXCHANGE EVP_PKEY_new_raw_public_key_ex when generating remote peer public key for X25519"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_NEW_RAW_PUBLIC_KEY_EX_X448 "KEY_EXCHANGE EVP_PKEY_new_raw_public_key_ex when generating remote peer public key for X448"
#define CW_ERROR_STR_KEY_EXCH_ECDH_GET_PEER_PUBLIC_KEY "KEY_EXCHANGE Generating remote peer public key failed for ECDH"
#define CW_ERROR_STR_KEY_EXCH_DERIVE_PUBLIC_KEY_WRONG_MODE "KEY_EXCHANGE Derive public key wrong mode"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_CTX_NEW_FROM_PKEY "KEY_EXCHANGE Deriving public key context from public key failed"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_DERIVE_INIT "KEY EXCHANGE EVP_PKEY_derive_init failed"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_DERIVE_SET_PEER "KEY EXCHANGE EVP_PKEY_derive_set_peer failed"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_DERIVE "KEY EXCHANGE EVP_PKEY_derive failed"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_GET_OCTET_STRING_PARAM "KEY EXCHANGE EVP_PKEY_get_octet_string_param failed"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_Q_KEYGEN_X25519 "KEY EXCHANGE EVP_PKEY_Q_keygen failed when generating key pair for X25519"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_NEW_RAW_PRIVATE_KEY_EX_CUSTOM_X25519 "KEY EXCHANGE EVP_PKEY_new_raw_private_key_ex failed when generating key pair from custom key for X25519"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_Q_KEYGEN_X448 "KEY EXCHANGE EVP_PKEY_Q_keygen failed when generating key pair for X448"
#define CW_ERROR_STR_KEY_EXCH_EVP_PKEY_NEW_RAW_PRIVATE_KEY_EX_CUSTOM_X448 "KEY EXCHANGE EVP_PKEY_new_raw_private_key_ex failed when generating key pair from custom key for X448"

/* MAC ERROR STRINGS */
#define CW_ERROR_STR_MAC_EVP_MAC_UPDATE "MAC EVP_MAC_update failed"
#define CW_ERROR_STR_MAC_EVP_MAC_FINAL "MAC EVP_MAC_final failed"
#define CW_ERROR_STR_MAC_EVP_MAC_CTX_NEW "MAC EVP_MAC_CTX_new failed"
#define CW_ERROR_STR_MAC_EVP_MAC_CTX_INIT "MAC EVP_MAC_init failed"
#define CW_ERROR_STR_MAC_EVP_MAC_CTX_SET_PARAMS "MAC EVP_MAC_CTX_set_params failed when trying to set custom mac out len"
#define CW_ERROR_STR_MAC_EVP_MAC_FETCH "MAC EVP_MAC_fetch failed when trying to load mac algorithm"
#define CW_ERROR_STR_MAC_VERIFY_LEN_MISMATCH "MAC verify generated mac is of different length from passed in mac"
#define CW_ERROR_STR_MAC_VERIFY_MAC_MISMATCH "MAC verify generated mac is different from passed in mac"
#define CW_ERROR_STR_MAC_SIPHASH_WRONG_KEY_LENGTH "MAC Siphash key needs to be 16 bytes long"
#define CW_ERROR_STR_MAC_SIPHASH_WRONG_OUTPUT_LENGTH "Mac Siphash output length needs to be 8 or 16 bytes long"

/* SYMETRIC CIPHER ERROR STRINGS */
#define CW_ERROR_STR_SYM_CIPHER_WRONG_KEY_LEN "SYMETRIC CIPHER wrong key size"
#define CW_ERROR_STR_SYM_CIPHER_WRONG_IV_LEN "SYMETRIC CIPHER wrong iv size"
#define CW_ERROR_STR_SYM_CIPHER_INPUT_SIZE_TOO_SHORT_FOR_XTS "SYMETRIC CIPHER Input size smaller than blocksize(16) for xts -> needs to be >= 16"
#define CW_ERROR_STR_SYM_CIPHER_EVP_CIPHER_CTX_NEW "SYMETRIC CIPHER EVP_CIPHER_CTX_new failed"
#define CW_ERROR_STR_SYM_CIPHER_EVP_CIPHER_INIT_EX2 "SYMETRIC CIPHER EVP_CipherInit_ex2 failed"
#define CW_ERROR_STR_SYM_CIPHER_EVP_CIPHER_UPDATE "SYMETRIC CIPHER EVP_CipherUpdate failed"
#define CW_ERROR_STR_SYM_CIPHER_EVP_CIPHERFINAL_EX "SYMETRIC CIPHER EVP_CipherFinal_ex failed"
#define CW_ERROR_STR_SYM_CIPHER_HIGH_MAC_MISMATCH "SYMETRIC CIPHER Mac of ciphertext does not match generated mac"
#define CW_ERROR_STR_SYM_CIPHER_STREAM_MODE_NOT_ALLOWED "SYMETRIC CIPHER algorithm is not allowed for stream interface"
#define CW_ERROR_STR_SYM_CIPHER_HIGH_WRONG_KEY_LENGTH "SYMETRIC CIPHER HIGH key length is not equal to length of the key used for encryption"

/* RSA ERROR STRINGS */
#define CW_ERROR_STR_RSA_WRONG_PADDING_MODE "RSA Wrong padding mode"
#define CW_ERROR_STR_RSA_KEY_SIZE_TOO_SMALL "RSA Key size too small -> needs to be >= 512"
#define CW_ERROR_STR_RSA_OSSL_ENCODER_CTX_NEW_FOR_PKEY "RSA OSSL_ENCODER_CTX_new_for_pkey failed"
#define CW_ERROR_STR_RSA_OSSL_ENCODER_CTX_SET_CIPHER "RSA OSSL_ENCODER_CTX_set_cipher failed when setting cipher for serialization"
#define CW_ERROR_STR_RSA_OSSL_ENCODER_CTX_SET_PASSPHRASE "RSA OSSL_ENCODER_CTX_set_passphrase failed when setting passphrase"
#define CW_ERROR_STR_RSA_OSSL_ENCODER_TO_FP "RSA OSSL_ENCODER_to_fp failed"
#define CW_ERROR_STR_RSA_OSSL_DECODER_CTX_NEW_FOR_PKEY "RSA OSSL_DECODER_CTX_new_for_pkey failed"
#define CW_ERROR_STR_RSA_OSSL_DECODER_CTX_SET_PASSPHRASE "RSA OSSL_DECODER_CTX_set_passphrase failed when setting passphrase"
#define CW_ERROR_STR_RSA_OSSL_OSSL_DECODER_FROM_FP "RSA OSSL_DECODER_from_fp failed"
#define CW_ERROR_STR_RSA_EVP_MD_CTX_NEW "RSA EVP_MD_CTX_new failed when signing"
#define CW_ERROR_STR_RSA_EVP_DIGEST_SIGN_INIT_EX "RSA EVP_DigestSignInit_ex failed"
#define CW_ERROR_STR_RSA_EVP_DIGEST_SIGN_UPDATE "RSA EVP_DigestSignUpdate failed"
#define CW_ERROR_STR_RSA_EVP_DIGEST_SIGN_FINAL "RSA EVP_DigestSignFinal failed"
#define CW_ERROR_STR_RSA_EVP_DIGEST_VERIFY_INIT_EX "RSA EVP_DigestVerifyInit_ex failed"
#define CW_ERROR_STR_RSA_EVP_DIGEST_VERIFY_UPDATE "RSA EVP_DigestVerifyUpdate failed"
#define CW_ERROR_STR_RSA_EVP_DIGEST_VERIFY_FINAL "RSA EVP_DigestVerifyFinal failed -> signature is not valid"
#define CW_ERROR_STR_RSA_EVP_PKEY_CTX_NEW_ID "RSA EVP_PKEY_CTX_new_id failed -> key size needs to be greater or equal than 512"
#define CW_ERROR_STR_RSA_EVP_PKEY_KEYGEN_INIT "RSA EVP_PKEY_keygen_init failed"
#define CW_ERROR_STR_RSA_EVP_PKEY_GENERATE "RSA EVP_PKEY_generate failed"
#define CW_ERROR_STR_RSA_SIGN_MESSAGE_TO_SHORT "RSA Sign message too short"
#define CW_ERROR_STR_RSA_VERIFY_MESSAGE_TO_SHORT "RSA Verify message too short"
#define CW_ERROR_STR_RSA_EVP_PKEY_CTX_SET_RSA_KEYGEN_BITS "RSA EVP_PKEY_CTX_set_rsa_keygen_bits failed"
#define CW_ERROR_STR_RSA_EVP_PKEY_CTX_SET_RSA_KEYGEN_PRIMES "RSA EVP_PKEY_CTX_set_rsa_keygen_primes failed"
#define CW_ERROR_STR_RSA_WRONG_SERIALIZATION_TYPE "RSA wrong serialization type"
#define CW_ERROR_STR_RSA_WRONG_SIGN_ALGORITHM "RSA wrong signing algorithm"  
#define CW_ERROR_STR_RSA_EVP_PKEY_CTX_SET_RSA_PADDING "RSA EVP_PKEY_CTX_set_rsa_padding failed"
#define CW_ERROR_STR_RSA_SIGNATURE_MODE_NOT_ALLOWED_FOR_X931 "RSA Signature mode not allowed for X931 padding"
#define CW_ERROR_STR_RSA_PADDING_MODE_NOT_ALLOWED_FOR_SIGNING "RSA Padding not allowed for signing"
#define CW_ERROR_STR_RSA_EVP_PKEY_CTX_NEW "RSA EVP_PKEY_CTX_new failed"
#define CW_ERROR_STR_RSA_EVP_PKEY_ENCRYPT_INIT_EX "RSA EVP_PKEY_encrypt_init_ex failed"
#define CW_ERROR_STR_RSA_EVP_PKEY_CTX_SET_RSA_OAEP_MD "RSA EVP_PKEY_CTX_set_rsa_oaep_md failed"
#define CW_ERROR_STR_RSA_EVP_PKEY_ENCRYPT "RSA EVP_PKEY_encrypt failed"
#define CW_ERROR_STR_RSA_EVP_PKEY_DECRYPT "RSA EVP_PKEY_decrypt failed"
#define CW_ERROR_STR_RSA_DER_PASSPHRASE_NOT_ALLOWED "RSA passphrase is not allowed when using DER"
#define CW_ERROR_STR_RSA_PSS_PADDING_MODE_NOT_ALLOWED_FOR_ENCRYPTION "RSA PSS padding mode not allowed for en- or decryption"

/* FETCH ERROR STRINGS */   
#define CW_ERROR_STR_FETCH_EVP_CIPHER_FETCH "FETCH EVP_CIPHER_fetch failed"
#define CW_ERROR_STR_FETCH_WRONG_EC_SERIALIZATION_TYPE "FETCH wrong ec serialization type"
#define CW_ERROR_STR_FETCH_WRONG_HASH_ALGORITHM "FETCH wrong hash algorithm"
#define CW_ERROR_STR_FETCH_WRONG_EC_CURVE "FETCH wrong ec curve type"
#define CW_ERROR_STR_FETCH_OSSL_PROVIDER_LOAD_LEGACY "FETCH OSSL_PROVIDER_load failed when loading legacy provider"
#define CW_ERROR_STR_FETCH_EVP_MD_fetch "FETCH EVP_MD_fetch failed when trying to load hash algorithm"
#define CW_ERROR_STR_FETCH_WRONG_SYMETRIC_CIPHER_MODE "FETCH wrong symetric cipher mode"
#define CW_ERROR_STR_FETCH_WRONG_CMAC_MODE "FETCH wrong cmac mode"
#define CW_ERROR_STR_FETCH_WRONG_KMAC_MODE "FETCH wrong kmac mode"
#define CW_ERROR_STR_FETCH_WRONG_ARGON_2_MODE "FETCH wrong argon2 mode"

/* RANDOM ERROR STRING */
#define CW_ERROR_STR_RANDOM_RAND_BYTES "RANDOM RAND_BYTES failed"

/* ALLOCATION ERRORS */
#define CW_ERROR_STR_ALLOC_OPENSSL_ZALLOC "OPENSSL ZALLOC failed"
#define CW_ERROR_STR_ALLOC_OPENSSL_CLEAR_REALLOC "OPENSSL CLEAR REALLOC failed"

/* MISC ERROS */
#define CW_ERROR_STR_FILE_COULD_NOT_OPEN "FILE could not open file"

/* KEY DERIVATION ERROR STRING */
#define CW_ERROR_STR_KEY_DERIVATION_KDF_AQUIRE_CONTEXT "KEY DERIVATION kdf_aquire_context failed"
#define CW_ERROR_STR_KEY_DERIVATION_KDF_DERIVE "KEY DERIVATION EVP_KDF_derive failed"
#define CW_ERROR_STR_KEY_DERIVATION_EVP_KDF_CTX_NEW "KEY DERIVATION EVP_KDF_CTX_new failed"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_OUTPUT_PTR_NULL "KEY DERIVATION ARGON2 output ptr null"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_OUTPUT_TOO_SHORT "KEY DERIVATION ARGON2 output too short"     
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_OUTPUT_TOO_LONG "KEY DERIVATION ARGON2 output too long"      
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_PWD_TOO_SHORT "KEY DERIVATION ARGON2 pwd too short"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_PWD_TOO_LONG "KEY DERIVATION ARGON2 pwd too long"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_SALT_TOO_SHORT "KEY DERIVATION ARGON2 salt too short"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_SALT_TOO_LONG "KEY DERIVATION ARGON2 salt too long"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_AD_TOO_SHORT "KEY DERIVATION ARGON2 ad too short"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_AD_TOO_LONG "KEY DERIVATION ARGON2 ad too long"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_SECRET_TOO_SHORT "KEY DERIVATION ARGON2 secret too short"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_SECRET_TOO_LONG "KEY DERIVATION ARGON2 secret too long"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_TIME_TOO_SMALL "KEY DERIVATION ARGON2 time to small"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_TIME_TOO_LARGE "KEY DERIVATION ARGON2 time too large"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_MEMORY_TOO_LITTLE "KEY DERIVATION ARGON2 memory too little"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_MEMORY_TOO_MUCH "KEY DERIVATION ARGON2 memory too much"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_LANES_TOO_FEW "KEY DERIVATION ARGON2 lanes to few"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_LANES_TOO_MANY "KEY DERIVATION ARGON2 lanes too many"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_PWD_PTR_MISMATCH "KEY DERIVATION ARGON2 pwd ptr mismatch"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_SALT_PTR_MISMATCH "KEY DERIVATION ARGON2 salt ptr mismatch"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_SECRET_PTR_MISMATCH "KEY DERIVATION ARGON2 secret ptr mismatch"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_AD_PTR_MISMATCH "KEY DERIVATION ARGON2 ad ptr mismatch"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_MEMORY_ALLOCATION_ERROR "KEY DERIVATION ARGON2 memory allocation error"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_FREE_MEMORY_CBK_NULL "KEY DERIVATION ARGON2 free memory cbk null"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_ALLOCATE_MEMORY_CBK_NULL "KEY DERIVATION ARGON2 memory cbk null"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_INCORRECT_PARAMETER "KEY DERIVATION ARGON2 incorrect parameter"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_INCORRECT_TYPE "KEY DERIVATION ARGON2 incorrect type"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_OUT_PTR_MISMATCH "KEY DERIVATION ARGON2 out ptr mismatch"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_THREADS_TOO_FEW "KEY DERIVATION ARGON2 threads too few"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_THREADS_TOO_MANY "KEY DERIVATION ARGON2 threads too many"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_MISSING_ARGS "KEY DERIVATION ARGON2 missing args"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_ENCODING_FAIL "KEY DERIVATION ARGON2 encoding fail"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_DECODING_FAIL "KEY DERIVATION ARGON2 decoding fail"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_THREAD_FAIL "KEY DERIVATION ARGON2 thread fail"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_DECODING_LENGTH_FAIL "KEY DERIVATION ARGON2 decoding length fail"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_VERIFY_MISMATCH "KEY DERIVATION ARGON2 verify mismtach"
#define CW_ERROR_STR_KEY_DERIVATION_ARGON2_UNKNOWN_ERROR_CODE "KEY DERIVATION ARGON 2 unknwon error"
#define CW_ERROR_STR_KEY_DERIVATION_EVP_KDF_CTX_GET_KDF_SIZE "KEY DERIVATION EVP_KDF_CTX_get_kdf_size failed"
#define CW_ERROR_STR_KEY_DERIVATION_EVP_KDF_FETCH "KEY DERIVATION EVP_KDF_fetch failed"
#define CW_ERROR_STR_KEY_DERIVATION_PBKDF2_VERIFY "KEY DERIVATION PBKDF2 verification failed"
#define CW_ERROR_STR_KEY_DERIVATION_HKDF_VERIFY "KEY DERIVATION HKDF verification failed"
#define CW_ERROR_STR_KEY_DERIVATION_HKDF_WRONG_OUTPUT_LEN "KEY DERIVATION HKDF output length too large -> needs to be smaller or equal to (hash_size(in bytes) * 255)"
#define CW_ERROR_STR_KEY_DERIVATION_SCRYPT_VERIFY "KEY DERIVATION SCRYPT verification failed"
#define CW_ERROR_STR_KEY_DERIVATION_SCRYPT_N_NOT_VALID "KEY DERIVATION SCRYPT N ist not valid -> needs to be greater than 1 and a power of 2"
#define CW_ERROR_STR_KEY_DERIVATION_SCRYPT_OUPUT_SIZE_TOO_LARGE "KEY DERIVATION SCRYPT output size too large -> needs to be smaller or equal than (2^32 - 1) * 32"
#define CW_ERROR_STR_FETCH_WRONG_ARGON_2_VERSION "FETCH wrong argon2 version"


#endif
